
import "./globals.css";
import '../styles/AndiPage/main.css'
import './index.css'

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class='layout'>{children}</body>
    </html>
  );
}
